version: "3"

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  uploads-data:

services:
  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "3001:3001"
    environment:
      NEXT_PUBLIC_API_BASE_URL: "http://localhost:3000"
      PORT: 3001
    command: pnpm start
    depends_on:
      - back
    networks:
      - app-network

  back:
    build:
      context: .
      dockerfile: back/Dockerfile
    environment:
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=your_database_name
      - JWT_SECRET=your_jwt_secret
      - GOOGLE_BOOKS_API_KEY=your_api_key
      - EMAIL_USER=your_email_user
      - EMAIL_PASS=your_email_pass
      - CORS_ORIGIN=http://localhost:3001
      - NODE_ENV=production
    ports:
      - "3000:3000"

    depends_on:
      - db
    volumes:
      - uploads-data:/app/uploads
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=readmemore
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
