version: "3"

services:
  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "3001:3001"
    environment:
      NEXT_PUBLIC_API_BASE_URL: "http://localhost:3000"
      PORT: 3001
    command: pnpm start
