name: CI

on:
  push:
    branches:
      - master

jobs:
  verify-builds:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Installer pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: "8"

      # Étape 3 : Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: ./front/pnpm-lock.yaml

      # Étape 4 : Installer les dépendances frontend
      - name: Install frontend dependencies
        working-directory: ./front
        run: |
          pnpm install

      # Étape 5 : Build du frontend
      - name: Build frontend
        working-directory: ./front
        run: |
          pnpm build

      # Étape 6 : Installer les dépendances backend
      - name: Install backend dependencies
        working-directory: ./back
        run: |
          npm install

      # Étape 7 : Injecter les secrets dans l'environnement
      - name: Set up environment variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> ./back/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> ./back/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ./back/.env
          # Ajoute d'autres variables ici si nécessaire

      # Étape 8 : Vérification backend (tests ou build)
      - name: Verify backend
        working-directory: ./back
        run: |
          npm test
