name: CI

on:
  push:
    branches:
      - master

jobs:
  verify-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: "8"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      # Installer les dépendances frontend
      - name: Install frontend dependencies
        working-directory: ./front
        run: |
          pnpm install --frozen-lockfile

      # Build frontend
      - name: Build frontend
        working-directory: ./front
        run: |
          pnpm build

      # Vérifie le backend
      - name: Install backend dependencies
        working-directory: ./back
        run: |
          npm install

      # Tests backend (ou build si nécessaire)
      - name: Verify backend
        working-directory: ./back
        run: |
          npm test
